# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.5

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: linters
          command: |
            . venv/bin/activate
            inv lint --check

      - run:
          name: tests
          command: |
            . venv/bin/activate
            inv test

workflows:
  version: 2
  workflow:
    jobs:
    - build
